isite/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from . import views


app_name = 'isite'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<slug:slug>/', views.PageDetailView.as_view(), name='page'),
    path('post/<str:slug>/', views.PostDetailView.as_view(), name='post'),
    path('new/post/', views.PostCreateView.as_view(), name='post_new'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

isvoe/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('spblitgid/', include('litgid.urls')),
    path('', include('isite.urls')),


]

litgid/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from . import views


app_name = 'litgid'
urlpatterns = [
    path('', views.test, name='index'),
    path('newsletter/', include('newsletter.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT)

isite/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField


class Category(models.Model):
    name = models.CharField(max_length=20, verbose_name='Категория')
    slug = models.SlugField(allow_unicode=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Рубрика"
        verbose_name_plural = "Рубрики"


class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    category = models.ForeignKey(
        Category,
        related_name='posts',
        on_delete=models.CASCADE,
        verbose_name='Рубрика')
    published_at = models.DateField(
        auto_now=False,
        auto_now_add=False,
        verbose_name='Дата публикации')
    image = models.ImageField(upload_to='post_images', null=True, blank=True)
    text = HTMLField(verbose_name='Текст')
    author = models.ForeignKey(
        User,
        related_name='posts',
        on_delete=models.CASCADE,
        verbose_name="Автор")
    slug = models.SlugField(allow_unicode=True)

    def __str__(self):
        return self.title

    def get_previous_post(self):
        post = Post.objects.get(id=self.id-1)
        if post:
            return post
        return ''

    def get_next_post(self):
        return Post.objects.get(id=self.id+1)

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"
        ordering = ['-published_at']


class Page(models.Model):
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    text = HTMLField(verbose_name="Текст")
    image = models.ImageField(upload_to='post_images', null=True, blank=True)
    parent = models.ForeignKey(
        "self",
        related_name='parents',
        on_delete=models.CASCADE,
        null=True,
        blank=True)
    slug = models.SlugField(allow_unicode=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Страница"
        verbose_name_plural = "Страницы"

litgid/models.py
from django.contrib.auth.models import User
from django.db import models


class Letter(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    date = models.DateField(blank=True, auto_now=False, auto_now_add=False, verbose_name='Дата публикации')


class Page(models.Model):
    title = models.CharField(max_length=100, verbose_name="Заголовок")
    text = models.TextField(verbose_name="Текст")
    slug = models.SlugField(allow_unicode=True)


    def __str__(self):
        return self.title

isite/forms.py
from tinymce.models import HTMLField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from .models import Post, Page, Category


class PostForm(forms.ModelForm):
    text = HTMLField()

    class Meta:
        model = Post
        fields = ['title', 'text', 'category']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', 'Отправить', css_class='form-submit'))

        self.helper.form_class = 'comment-form'
        self.helper.label_class = 'comment-form-comment'

isite/views.py
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.views.generic import View, CreateView, ListView

from .models import Post, Page
from .forms import PostForm


class IndexView(ListView):
    """
    Главная страница сайта: вывод пяти последних постов.
    """
    model = Post
    paginate_by = 5
    template_name = 'index.html'
    queryset = Post.objects.all()


class PostDetailView(DetailView):
    """
    Шаблон для одного поста.
    """
    model = Post


class PageDetailView(DetailView):
    """
    Шаблон для одной страницы.
    """
    model = Page


class PostCreateView(CreateView):
    """
    Форма для создания нового поста.
    """
    model = Post
    form_class = PostForm
    template_name = 'post_new.html'
    success_url = 'isite:post_detail.html'

litgid/views.py
from django.shortcuts import render


def test(request):
    return render(request, 'litgid/index.html', {})

templates/base.html
{% load static %}
{% include 'header.html' %}
{% include 'nav.html' %}<!-- #access -->
		</div><!-- #masthead -->
	</div><!-- #header -->

	<div id="main">

{% block content %}
{% endblock %}


		{% include 'sidebar.html' %}

</div><!-- #main -->

	{% include 'footer.html' %}

templates/footer.html
<div id="footer" role="contentinfo">
		<div id="colophon">
			<div id="footer-widget-area" role="complementary">
				<div id="first" class="widget-area">
					<ul class="xoxo">
						<li id="text-3" class="widget-container widget_text">
							<h3 class="widget-title">Телефон</h3>
							<div class="textwidget">(812) 900-21-45</div>
						</li>
					</ul>
				</div><!-- #first .widget-area -->

				<div id="second" class="widget-area">
					<ul class="xoxo">
						<li id="text-4" class="widget-container widget_text">
							<h3 class="widget-title">E-mail:</h3>
							<div class="textwidget">editor@isvoe.ru</div>
						</li>
					</ul>
				</div><!-- #second .widget-area -->

				<div id="third" class="widget-area">
					<ul class="xoxo">
						<li id="text-5" class="widget-container widget_text">
							<h3 class="widget-title">Время работы:</h3>
							<div class="textwidget">С понедельника по пятницу: <br>11.00—19.00.</div>
						</li>
					</ul>
				</div><!-- #third .widget-area -->


			</div><!-- #footer-widget-area -->

			<div id="site-info">
				<a href="http://isvoe.ru/" title="Издание и печать книг" rel="home">
					Издание и печать книг
				</a>
			</div><!-- #site-info -->

			<div id="site-generator">
								<a href="" class="imprint" title="">Сайт работает на Django.
								</a>
			</div><!-- #site-generator -->

		</div><!-- #colophon -->
	</div><!-- #footer -->

</div><!-- #wrapper -->

</body>

templates/header.html
<html lang="ru-RU">
<head>
<meta charset="UTF-8" />
<title>Издание и печать книг | С.-Петербург, 4-я линия В. О., д. 5 (812) 900-21-45	</title>

<link rel="profile" href="http://gmpg.org/xfn/11" />
<link rel="stylesheet" type="text/css" media="all" href="http://isvoe.ru/wp-content/themes/twentyten/style.css" />

<body class="home blog custom-background">
<div id="wrapper" class="hfeed">
	<div id="header">
		<div id="masthead">
			<div id="branding" role="banner">
				<h1 id="site-title">
					<span>
						<a href="{% url 'isite:index' %}" title="Издание и печать книг" rel="home">Издание и печать книг</a>
					</span>
				</h1>
				<div id="site-description">С.-Петербург, 4-я линия В. О., д. 5 (812) 900-21-45</div>
					<img src="http://isvoe.ru/wp-content/uploads/2013/06/shapka.jpg" width="940" height="129" alt="" />
				</div><!-- #branding -->

templates/index.html
{% extends 'base.html' %}

{% block content %}
		<div id="container">
			<div id="content" role="main">

{% for one_post in page_obj %}
			<div id="post-688" class="post-688 post type-post status-publish format-standard hentry category-avtorskie-knigi category-1">
			<h2 class="entry-title"><a href="{% url 'isite:post' one_post.slug %}">{{ one_post.title }}</a></h2>

			<div class="entry-meta">
				<span class="meta-prep meta-prep-author">Опубликовано</span> <span class="entry-date">{{ one_post.published_at|date }}</span> <span class="meta-sep">автором</span> <span class="author vcard"><a class="url fn n" href="http://isvoe.ru/author/admin/" title="Посмотреть все записи автора Редактор">{{ one_post.author.first_name }}</a></span>
			</div><!-- .entry-meta -->

			
			<div class="entry-content">
				{% if one_post.image %}
					<img src="{{MEDIA_URL}}{{ one_post.image }}" style='float:left;margin:15px'>
				{% endif %}
				{{ one_post.text|safe }}		
			</div><!-- .entry-content -->
	
			<div class="entry-utility">
				<span class="cat-links">
					<span class="entry-utility-prep entry-utility-prep-cat-links">Рубрика: </span><a href="http://isvoe.ru/category/avtorskie-knigi/" rel="category tag">{{ one_post.category.name }}</a>
				</span>
			</div><!-- .entry-utility -->	
		</div><!-- #post-## -->
{% endfor %}
		<div class="pagination">
		<div id="nav-below" class="navigation">
		{% if page_obj.has_previous %}
			<div class="nav-previous"><a href="?page={{ page_obj.previous_page_number }}" ><span class="meta-nav">&larr;</span> Предыдущие записи</a>
			</div>{% endif %}
			{% if page_obj.has_next %}
			<div class="nav-next"><a href="?page={{ page_obj.next_page_number }}" >Следующие записи <span class="meta-nav">&rarr;</span></a>
			</div>
			{% endif %}
		</div><!-- #nav-below -->
	</div>
	</div><!-- #content -->
</div><!-- #container -->

{% endblock %}

templates/isite/index.html
{% extends 'base.html' %}

{% block content %}
		<div id="container">
			<div id="content" role="main">

	
{% for one_post in fresh_posts %}
			<div id="post-688" class="post-688 post type-post status-publish format-standard hentry category-avtorskie-knigi category-1">
			<h2 class="entry-title"><a href="{% url 'isite:post' one_post.slug %}">{{ one_post.title }}</a></h2>

			<div class="entry-meta">
				<span class="meta-prep meta-prep-author">Опубликовано</span> <span class="entry-date">{{ one_post.published_at|date }}</span> <span class="meta-sep">автором</span> <span class="author vcard"><a class="url fn n" href="http://isvoe.ru/author/admin/" title="Посмотреть все записи автора Редактор">{{ one_post.author.first_name }}</a></span>
			</div><!-- .entry-meta -->

			
			<div class="entry-content">
				{% if one_post.image %}
					<img src="{{MEDIA_URL}}{{ one_post.image }}" style='float:left;margin:15px'>
				{% endif %}
				{{ one_post.text|safe }}		
			</div><!-- .entry-content -->
	
			<div class="entry-utility">
				<span class="cat-links">
					<span class="entry-utility-prep entry-utility-prep-cat-links">Рубрика: </span><a href="http://isvoe.ru/category/avtorskie-knigi/" rel="category tag">{{ one_post.category.name }}</a>
				</span>
			</div><!-- .entry-utility -->	
		</div><!-- #post-## -->
{% endfor %}
		
		<div id="nav-below" class="navigation">
			<div class="nav-previous"><a href="http://isvoe.ru/page/2/" ><span class="meta-nav">&larr;</span> Предыдущие записи</a>
			</div>
			<div class="nav-next"></div>
		</div><!-- #nav-below -->
	</div><!-- #content -->
</div><!-- #container -->

{% endblock %}

templates/isite/page_detail.html
{% extends 'base.html' %}

{% block content %}
		<div id="container">
			<div id="content" role="main">

				<div id="post-23" class="post-23 page type-page status-publish hentry">
											<h1 class="entry-title"> {{object.title }}</h1>					
					<div class="entry-content">
						{{ object.text|safe }}	
					</div><!-- .entry-content -->
				</div><!-- #post-## -->
				<!-- #nav-below -->
			</div><!-- #content -->
		</div><!-- #container -->

{% endblock %}

templates/isite/post_detail.html
{% extends 'base.html' %}

{% block content %}
		<div id="container">
			<div id="content" role="main">
				<div id="nav-above" class="navigation">
					{% if object.get_previous_post %}
					<div class="nav-previous"><a href="{% url 'isite:post' object.get_previous_post.slug %}" rel="prev"><span class="meta-nav">&larr;</span> {{ object.get_previous_post.title }}</a></div>
					{% endif %}
					{% if object.get_next_post %}
					<div class="nav-next"><a href="{% url 'isite:post' object.get_next_post.slug %}" rel="next">{{ object.get_next_post.title }} <span class="meta-nav">&rarr;</span></a></div>
					{% endif %}
				</div><!-- #nav-above -->

				<div id="post-1" class="post-1 post type-post status-publish format-standard hentry category-avtorskie-knigi">
					<h1 class="entry-title">{{ object.title}}</h1>

					<div class="entry-meta">
						<span class="meta-prep meta-prep-author">Опубликовано</span> <a href="http://isvoe.ru/vnezapno-stihi/" title="07:14" rel="bookmark"><span class="entry-date">{{ object.published_at|date }}</span></a> <span class="meta-sep">автором</span> <span class="author vcard"><a class="url fn n" href="http://isvoe.ru/author/admin/" title="Посмотреть все записи автора Редактор">{{ object.author }}</a></span>					</div><!-- .entry-meta -->

					<div class="entry-content">
						{% if object.image %}
					<img src="{{MEDIA_URL}}{{ object.image }}" style='float:left;margin:15px'>
					{% endif %}
					{{ object.text|safe }}
					</div><!-- .entry-content -->

	
						<div class="entry-utility">
							Запись опубликована в рубрике <a href="http://isvoe.ru/category/avtorskie-knigi/" rel="category tag">{{ object.category }}</a>. Добавьте в закладки <a href="{% url 'isite:post' object.slug %}" title="Постоянная ссылка: внезапно стихи" rel="bookmark">постоянную ссылку</a>.							<span class="edit-link"><a class="post-edit-link" href="http://isvoe.ru/wp-admin/post.php?post=1&#038;action=edit">Изменить</a></span>						</div><!-- .entry-utility -->
					</div><!-- #post-## -->

					<div id="nav-below" class="navigation">
						{% if object.get_previous_post %}
						<div class="nav-previous"><a href="{% url 'isite:post' object.get_previous_post.slug %}" rel="prev"><span class="meta-nav">&larr;</span> {{ object.get_previous_post.title }}</a></div>
						{% endif %}
						{% if object.get_next_post %}
						<div class="nav-next"><a href="{% url 'isite:post' object.get_next_post.slug %}" rel="next">{{ object.get_next_post.title}} <span class="meta-nav">&rarr;</span></a></div>
						{% endif %}
					</div><!-- #nav-below -->
			</div><!-- #content -->
		</div><!-- #container -->

{% endblock %}

templates/isite/post_new.html
{% extends 'base.html' %}
{%  load crispy_forms_tags %}
{% block content %}

		<div id="container">
			<div id="content" role="main">
                  <form action="" method="post" class='comment-form'>

                      {{ form }}
                      <div class='form-actions'>
                          <input type="submit" value="Submit" class="btn btn-primary">
                      </div>
                  </form>
            </div><!-- #content -->
		</div><!-- #container -->

{% endblock %}

templates/litgid/index.html
{% extends 'litgid_base.html' %}

{% block content %}

{%  endblock %}

templates/litgid_base.html
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" lang="ru-RU">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" lang="ru-RU">
<![endif]-->
<!--[if !(IE 7) & !(IE 8)]><!-->
<html lang="ru-RU">
<!--<![endif]-->
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width" />
<title>Об СПбЛитГиде | СПбЛитГид</title>

<link rel='stylesheet' id='twentytwelve-fonts-css'  href='https://fonts.googleapis.com/css?family=Open+Sans%3A400italic%2C700italic%2C400%2C700&#038;subset=latin%2Clatin-ext%2Ccyrillic%2Ccyrillic-ext&#038;display=fallback' type='text/css' media='all' />
<link rel='stylesheet' id='twentytwelve-style-css'  href='http://isvoe.ru/spblitgid/wp-content/themes/twentytwelve/style.css?ver=20190507' type='text/css' media='all' />
<link rel='stylesheet' id='twentytwelve-block-style-css'  href='http://isvoe.ru/spblitgid/wp-content/themes/twentytwelve/css/blocks.css?ver=20190406' type='text/css' media='all' />
<!--[if lt IE 9]>
<link rel='stylesheet' id='twentytwelve-ie-css'  href='http://isvoe.ru/spblitgid/wp-content/themes/twentytwelve/css/ie.css?ver=20150214' type='text/css' media='all' />
<![endif]-->
<script type='text/javascript' src='http://isvoe.ru/spblitgid/wp-includes/js/jquery/jquery.js?ver=1.12.4-wp' id='jquery-core-js'></script>
<link rel="https://api.w.org/" href="http://isvoe.ru/spblitgid/wp-json/" /><link rel="alternate" type="application/json" href="http://isvoe.ru/spblitgid/wp-json/wp/v2/pages/112" /><link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://isvoe.ru/spblitgid/wp-includes/wlwmanifest.xml" />
<meta name="generator" content="WordPress 5.5.3" />
<link rel="canonical" href="http://isvoe.ru/spblitgid/ob-spblitgide/" />
<link rel='shortlink' href='http://isvoe.ru/spblitgid/?p=112' />


	</head>

<body class="page-template-default page page-id-112 no-customize-support wp-embed-responsive custom-font-enabled">


		<div id="page" class="hfeed site">
	<header id="masthead" class="site-header" role="banner">
		<hgroup>
			<h1 class="site-title"><a href="http://isvoe.ru/spblitgid/" title="СПбЛитГид" rel="home">СПбЛитГид</a></h1>
			<h2 class="site-description">Санкт-Петербургский Литературный Гид</h2>
		</hgroup>

		<nav id="site-navigation" class="main-navigation" role="navigation">
			<button class="menu-toggle">Меню</button>
			<a class="assistive-text" href="#content" title="Перейти к содержимому">Перейти к содержимому</a>
			<div class="menu-menyu-1-container"><ul id="menu-menyu-1" class="nav-menu"><li id="menu-item-1377" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-1377"><a href="http://isvoe.ru/spblitgid/">Главная</a></li>
<li id="menu-item-1378" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1378"><a href="http://isvoe.ru/spblitgid/mesta/">Места</a></li>
<li id="menu-item-1379" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-112 current_page_item menu-item-1379"><a href="http://isvoe.ru/spblitgid/ob-spblitgide/" aria-current="page">Об СПбЛитГиде</a></li>
<li id="menu-item-1380" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1380"><a href="http://isvoe.ru/spblitgid/sample-page/">Принципы составления</a></li>
<li id="menu-item-1381" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1381"><a href="http://isvoe.ru/spblitgid/category/moslitgid/">МосЛитГид</a></li>
</ul></div>		</nav><!-- #site-navigation -->

			</header><!-- #masthead -->

	<div id="main" class="wrapper">

	<div id="primary" class="site-content">
		<div id="content" role="main">


	<article id="post-112" class="post-112 page type-page status-publish hentry">
		<header class="entry-header">
													<h1 class="entry-title">Об СПбЛитГиде</h1>
		</header>

		<div class="entry-content">
            {% block content %}
            {% endblock %}
					</div><!-- .entry-content -->
		<footer class="entry-meta">
			<span class="edit-link"><a class="post-edit-link" href="http://isvoe.ru/spblitgid/wp-admin/post.php?post=112&#038;action=edit">Изменить</a></span>		</footer><!-- .entry-meta -->
	</article><!-- #post -->

<div id="comments" class="comments-area">




</div><!-- #comments .comments-area -->

		</div><!-- #content -->
	</div><!-- #primary -->


			<div id="secondary" class="widget-area" role="complementary">
			<aside id="search-2" class="widget widget_search"><form role="search" method="get" id="searchform" class="searchform" action="http://isvoe.ru/spblitgid/">
				<div>
					<label class="screen-reader-text" for="s">Найти:</label>
					<input type="text" value="" name="s" id="s" />
					<input type="submit" id="searchsubmit" value="Поиск" />
				</div>
			</form></aside>

                <aside>
                    <form enctype="multipart/form-data" method="post" action="">
                        {% csrf_token %}
                        <label for="id_email_field">E-mail:</label><br/>
                        <input type="email" name="email_field" required="" id="id_email_field">
                        <button id="id_submit" name="submit" value="Subscribe" type="submit">Subscribe</button>
                    </form>
                </aside>


		<aside id="recent-posts-2" class="widget widget_recent_entries">
		<h3 class="widget-title">Последние рассылки</h3>
		<ul>
											<li>
					<a href="http://isvoe.ru/spblitgid/2020/12/01/spblitguide-20-12-1/">SPbLitGuide 20-12-1</a>
									</li>

			</ul>

			</aside><aside id="meta-2" class="widget widget_meta"><h3 class="widget-title">Мета</h3>
		<ul>
			<li><a href="http://isvoe.ru/spblitgid/wp-admin/">Управление сайтом</a></li>			<li><a href="http://isvoe.ru/spblitgid/wp-login.php?action=logout&#038;_wpnonce=ab347f2bed">Выйти</a></li>
			<li><a href="http://isvoe.ru/spblitgid/feed/">Лента записей</a></li>
			<li><a href="http://isvoe.ru/spblitgid/comments/feed/">Лента комментариев</a></li>

			<li><a href="https://ru.wordpress.org/">WordPress.org</a></li>
		</ul>

		</aside>		</div><!-- #secondary -->
		</div><!-- #main .wrapper -->
	<footer id="colophon" role="contentinfo">
		<div class="site-info">
									<a href="https://ru.wordpress.org/" class="imprint" title="Современная персональная платформа для публикаций">
				Сайт работает на WordPress			</a>
		</div><!-- .site-info -->
	</footer><!-- #colophon -->
</div><!-- #page -->


</body>
</html>

templates/nav.html
<div id="access" role="navigation">
	<div class="skip-link screen-reader-text"><a href="#content" title="Перейти к содержимому">Перейти к содержимому</a></div>
	<div class="menu-header">
		<ul id="menu-1" class="menu">
			{% for page in pages %}
			<li id="menu-item-70" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-70"><a href="{% url 'isite:page' page.slug %}">{{ page.title}}</a>
				<ul class="sub-menu">
					{% for p in page.parents.all %}
					<li id="menu-item-71" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-71"><a href="{% url 'isite:page' p.slug %}">{{ p.title }}</a></li>
					{% endfor %}
				</ul>
				{% endfor %}
			</li>
		</ul>
	</div>
</div>
|

templates/post_new.html
{% extends 'base.html' %}
{%  load crispy_forms_tags %}
{% block content %}

		<div id="container">
			<div id="content" role="main">
                <div id="respond" class="comment-respond">
                    <h3 id="reply-title" class="comment-reply-title">Добавить пост</h3>
                  <form action="" method="post" class='comment-form'>

                      {% crispy form %}

                  </form>
                </div>
            </div><!-- #content -->
		</div><!-- #container -->

{% endblock %}

templates/sidebar.html
<div id="primary" class="widget-area" role="complementary">
			<ul class="xoxo">

<li id="custom_html-2" class="widget_text widget-container widget_custom_html"><h3 class="widget-title">Дорогие авторы!</h3><div class="textwidget custom-html-widget">В связи с пандемией и плановым ремонтом здания на 4-й линии В. О., где размещается офис издательства, мы переходим до конца августа на удаленный режим работы. Мы остаемся на связи по электронной почте и по телефону, готовые книги будут доставляться курьерской службой или с помощью такси. В случае необходимости о личной встрече можно договориться заранее по телефону издательства: (812) 900-21-45.</div></li>
<li id="search-2" class="widget-container widget_search">
	<form role="search" method="get" id="searchform" class="searchform" action="http://isvoe.ru/">
				<div>
					<label class="screen-reader-text" for="s">Найти:</label>
					<input type="text" value="" name="s" id="s" />
					<input type="submit" id="searchsubmit" value="Поиск" />
				</div>
			</form></li>
<li id="nav_menu-2" class="widget-container widget_nav_menu"><h3 class="widget-title">Все о печати книг</h3><div class="menu-1-container"><ul id="menu-2" class="menu">
{% for page in pages %}
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-70"><a href="{% url 'isite:page' page.slug %}">{{ page.title}}</a>
	
<ul class="sub-menu">{% for p in page.parents.all %}
	<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-71"><a href="{% url 'isite:page' p.slug %}">{{ p.title }}</a></li>
	{% endfor %}
</ul>
</li>
{% endfor %}
<li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-497"><a href="http://isvoe.ru/knigi-svoego-izdatelstva-vrem/">Наши книги</a></li>
</ul></div></li>
<li id="recent-posts-2" class="widget-container widget_recent_entries">		<h3 class="widget-title">Свежие записи</h3>		
	<ul>
		{% for post in fresh_posts %}
		<li>
			<a href="{% url 'isite:post' post.slug %}">{{ post.title }}</a>
		</li>
		{% endfor %}
	</ul>
</li>
</ul>

</div><!-- #primary .widget-area -->